name: sync-blob

on:
  workflow_dispatch:
  schedule:
  - cron: "30 1,9,17 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: data
    
    - name: filter incremental data
      run: |
        mkdir -p .tmp/data
        INDEX=`curl https://neoburger.blob.core.windows.net/data/index`
        while [ -f ./data/${INDEX}.json ];do echo ./data/${INDEX}.json && cp ./data/${INDEX}.json .tmp/data/${INDEX}.json && INDEX=$((INDEX+1));done
        echo $INDEX > .tmp/index
        
    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        inlineScript: 
          az storage blob upload-batch --destination data --source .tmp/data --account-name neoburger --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
          az storage blob upload --container-name data --file .tmp/index --account-name neoburger --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}

