name: sync-blob

on:
  workflow_dispatch:
  schedule:
  - cron: "30 1,9,17 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: data
    
    - name: filter incremental data
      run: |
        mkdir -p .tmp/data
        INDEX=`curl https://neoburger.blob.core.windows.net/data/index`
        HEX=`printf "%08X\n" $INDEX`
        SRC=data/${HEX:0:1}/${HEX:1:1}/${HEX:2:1}/${HEX:3:1}/${HEX:4:1}/${HEX:5:1}/${HEX:6:1}/${HEX:7:1}/${INDEX}.json
        while [ -f $SRC ];do echo $SRC && cp $SRC .tmp/data/${INDEX}.json && INDEX=$((INDEX+1)); HEX=`printf "%08X\n" $INDEX`;SRC=data/${HEX:0:1}/${HEX:1:1}/${HEX:2:1}/${HEX:3:1}/${HEX:4:1}/${HEX:5:1}/${HEX:6:1}/${HEX:7:1}/${INDEX}.json;done
        echo $INDEX > .tmp/index
        
    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az storage blob upload-batch --overwrite true --destination data --source .tmp/data --account-name neoburger --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
          az storage blob upload --overwrite true --container-name data --file .tmp/index --account-name neoburger --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}

