name: sync-blob

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: data
        
    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        inlineScript: 
          az storage blob sync -c data -s ./data --account-name neoburger --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        
          
